### ISSUE TITLE
Changelog to display readable guide based changes

### ISSUE THREAD

**Issue by Kromula** [thevinter/react-dreamgrove#2]
**Is your feature request related to a problem? Please describe.**
I think it is difficult and in parts challenging to keep up to date with Guide based changes, where the changelog goes directly to Github commits. While I work with Github and understand how to use it (but potentially majority does not) it still feels excessive having to read commits to see guide based changes. 

To be clear this is only in relation to game based content, not the framework or technicals behind the Compendium itself. 

**Describe the solution you'd like**
I would like the Changelog to be a section that includes some brief release notes indicating changes. 

EG:

02/06/2024
- _Trinket X has been removed from the trinket section as this was discovered as a simulation issue_
- _Ring Y has been added to Gearing as it [insert reason]_

10/07/2024
- _Updated rotation section to remove [spell] as it was identified [reason]_

**Describe alternatives you've considered**
I feel having the Changelog being a section where there is a brief release note style structure could help users quickly identify changes that have occurred. 

Could be possible News section is repurposed to house this changelog. 

Could also be possible to create a text based file in the repo, and have the Changelog link go to there instead of the commit page. This text based file could be a release note style file where easily consumed release/changes can be read. 

**Additional context**
To be clear I feel this is only needed for content related to the guide itself or in game content. Changes/commits done for the framework of the page (CSS, alignments, coding etc.) does not need to be included.

**Comment by thevinter** [comment]
Hey, thanks for the suggestion. To have a seamless deploy we ended up using multiple repositories and unfortunately some links are not yet updated. This repository will be closed in the following days. Could you please reopen the same issue on the main dreamgrove repo: https://github.com/dreamgrove/dreamgrove/issues 

Thanks!

**Comment by thevinter** [comment]
Hey, thanks for the suggestion. To have a seamless deploy we ended up using multiple repositories and unfortunately some links are not yet updated. This repository will be closed in the following days. Could you please reopen the same issue on the main dreamgrove repo: https://github.com/dreamgrove/dreamgrove/issues 

Thanks!

**Comment by thevinter** [comment]
Took the liberty to move it: https://github.com/dreamgrove/dreamgrove/issues/545
